// Layer
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

// Tap-Hold Configuration
#define TAPPING_TERM 150
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

// Combo
#define COMBO_TERM 50
#define COMBO_HOLD_TERM 100
#define COMBO_TERM_PER_COMBO
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_MUST_HOLD_PER_COMBO

// Caps Word
#define CAPS_WORD_IDLE_TIMEOUT 0
