#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define TAPPING_TERM 150
#define QUICK_TAP_TERM 0
#define COMBO_TERM 20
#define COMBO_HOLD_TERM 100
#define CAPS_WORD_IDLE_TIMEOUT 0
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_MUST_HOLD_PER_COMBO
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
